steps:
  - name: 'docker.io/hadolint/hadolint:v1.17.2'
    id: Lint Dockerfile
    args: ["hadolint", "Dockerfile"]
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Build Image
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/terraform-testing:${SHORT_SHA}"
      - "--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}"
      - "--build-arg=TFLINT_VERSION=${_TFLINT_VERSION}"
      - "--build-arg=GOLANG_VERSION=${_GOLANG_VERSION}"
      - "."
    waitFor:
      - Lint Dockerfile
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Push Image (Short SHA)
    args:
      - push
      - gcr.io/$PROJECT_ID/terraform-testing:${SHORT_SHA}
    waitFor:
      - Build Image
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Tag Image (TF Version)
    args:
      - tag
      - gcr.io/$PROJECT_ID/terraform-testing:${SHORT_SHA}
      - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}
    waitFor:
      - Build Image
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Push Image (TF Version)
    args:
      - push
      - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}
    waitFor:
      - Tag Image (TF Version)
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Tag Image (TF Version and Short SHA)
    args:
      - tag
      - gcr.io/$PROJECT_ID/terraform-testing:${SHORT_SHA}
      - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}-${SHORT_SHA}
    waitFor:
      - Build Image
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: Push Image (TF Version and Short SHA)
    args:
      - push
      - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}-${SHORT_SHA}
    waitFor:
      - Tag Image (TF Version and Short SHA)
images:
  - gcr.io/$PROJECT_ID/terraform-testing:${SHORT_SHA}
  - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}
  - gcr.io/$PROJECT_ID/terraform-testing:${_TERRAFORM_VERSION}-${SHORT_SHA}
substitutions:
  _TERRAFORM_VERSION: "0.12.13"
  _TFLINT_VERSION: "0.12.1"
  _GOLANG_VERSION: "1.13.4"
